//// <auto-generated />
//using IndeedIQ.Security.Infrastructure.Repositories;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Migrations;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace IndeedIQ.Security.Infrastructure.Repositories.Migrations
//{
//    [DbContext(typeof(SecurityDataContext))]
//    [Migration("20210223225723_Initial")]
//    partial class Initial
//    {
//        protected override void BuildTargetModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.ResourceAggregate.ApplicationResource", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("ApplicationLevel")
//                        .IsRequired()
//                        .HasMaxLength(40)
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(40)
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("ApplicationResource");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.ResourceAggregate.ResourceAction", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("FullName")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(30)
//                        .HasColumnType("TEXT");

//                    b.Property<long>("ResourceId")
//                        .HasColumnType("INTEGER");

//                    b.HasKey("Id");

//                    b.HasIndex("ResourceId");

//                    b.ToTable("ResourceAction");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.RoleAggregate.Role", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(30)
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("Role");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.RoleAggregate.RoleActionPermission", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<long>("ActionId")
//                        .HasColumnType("INTEGER");

//                    b.Property<int>("Permission")
//                        .HasColumnType("INTEGER");

//                    b.Property<long>("RoleId")
//                        .HasColumnType("INTEGER");

//                    b.HasKey("Id");

//                    b.HasIndex("ActionId");

//                    b.HasIndex("RoleId");

//                    b.ToTable("RoleActionPermission");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.UserAggregate.User", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("Country")
//                        .IsRequired()
//                        .HasMaxLength(2)
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Currency")
//                        .IsRequired()
//                        .HasMaxLength(3)
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Email")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("IdentityServerId")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Login")
//                        .IsRequired()
//                        .HasMaxLength(150)
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Name")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("TEXT");

//                    b.HasKey("Id");

//                    b.ToTable("User");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.UserAggregate.UserRole", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("INTEGER");

//                    b.Property<string>("Accounts")
//                        .HasColumnType("TEXT");

//                    b.Property<string>("Organisations")
//                        .HasColumnType("TEXT");

//                    b.Property<long>("RoleId")
//                        .HasColumnType("INTEGER");

//                    b.Property<long>("UserId")
//                        .HasColumnType("INTEGER");

//                    b.HasKey("Id");

//                    b.HasIndex("RoleId");

//                    b.HasIndex("UserId");

//                    b.ToTable("UserRole");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.ResourceAggregate.ResourceAction", b =>
//                {
//                    b.HasOne("IndeedIQ.Security.Domain.Entities.ResourceAggregate.ApplicationResource", "Resource")
//                        .WithMany("AvailableActions")
//                        .HasForeignKey("ResourceId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Resource");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.RoleAggregate.RoleActionPermission", b =>
//                {
//                    b.HasOne("IndeedIQ.Security.Domain.Entities.ResourceAggregate.ResourceAction", "Action")
//                        .WithMany()
//                        .HasForeignKey("ActionId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("IndeedIQ.Security.Domain.Entities.RoleAggregate.Role", "Role")
//                        .WithMany("RolePermissions")
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Action");

//                    b.Navigation("Role");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.UserAggregate.UserRole", b =>
//                {
//                    b.HasOne("IndeedIQ.Security.Domain.Entities.RoleAggregate.Role", "Role")
//                        .WithMany()
//                        .HasForeignKey("RoleId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.HasOne("IndeedIQ.Security.Domain.Entities.UserAggregate.User", "User")
//                        .WithMany("Roles")
//                        .HasForeignKey("UserId")
//                        .OnDelete(DeleteBehavior.Cascade)
//                        .IsRequired();

//                    b.Navigation("Role");

//                    b.Navigation("User");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.ResourceAggregate.ApplicationResource", b =>
//                {
//                    b.Navigation("AvailableActions");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.RoleAggregate.Role", b =>
//                {
//                    b.Navigation("RolePermissions");
//                });

//            modelBuilder.Entity("IndeedIQ.Security.Domain.Entities.UserAggregate.User", b =>
//                {
//                    b.Navigation("Roles");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
